<div id="arriba" class="row">
    <div class="col-sm-12">
        <nav>
            <ul>
                <li><a href="index.php">Iniciooo</a></li>
                <li><a href="fotos.php">Fotos</a></li>
                <li><a href="info.php">Info.</a></li>
                <li><a href="insertar.php">Insertar</a></li>
                <li><a href="mostrar.php">Mostrar</a></li>
                <li><a href="mostrar.php">Eliminar</a></li>
                <li><a href="contacto.php">Contacto</a></li>
            </ul>
        </nav>
    </div>
</div>

<?php
include "conexion.inc";
?>